# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d2ba79c0802057f37fef20e37562337f4794566abd2c727e4e1668b97a073974fae4fb7598c1d27d7f2b2d677f1d083456a3ba37856ebb9462af13c6fe166aa

test:
  secret_key_base: d63971fecd110096217c0bc35f13a893acb716826877f88ce7dcc4e8fdc7c2cb7bbd5c09a7ee43e4ca11cedc3bfd1a2afe1522a6406f103f854cc92789655dcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
